## Cek data

    ABUSIVE
0      alay
1     ampas
2      buta
3   keparat
4    anjing
5     anjir
6      babi
7     bacot
8  bajingan
9     banci

                  original                        replacement
0      anakjakartaasikasik           anak jakarta asyik asyik
1             pakcikdahtua                  pak cik sudah tua
2           pakcikmudalagi                  pak cik muda lagi
3              t3tapjokowi                       tetap jokowi
4                       3x                          tiga kali
...                    ...                                ...
15162            mendikbud  menteri pendidikan dan kebudayaan
15163               mendag                menteri perdagangan
15164              menaker               menteri tenaga kerja
15165             memetwit                            mentwit
15166             megangin                           memegang

[15167 rows x 2 columns]

# Load semua data yang dipakai

Shape:  (13169, 13)

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,- disaat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,RT USER: USER siapa yang telat ngasih tau elu?...,0,1,0,0,0,0,0,0,0,0,0,0
2,"41. Kadang aku berfikir, kenapa aku tetap perc...",0,0,0,0,0,0,0,0,0,0,0,0
3,USER USER AKU ITU AKU\n\nKU TAU MATAMU SIPIT T...,0,0,0,0,0,0,0,0,0,0,0,0
4,USER USER Kaum cebong kapir udah keliatan dong...,1,1,0,1,1,0,0,0,0,0,1,0
5,USER Ya bani taplak dkk \xf0\x9f\x98\x84\xf0\x...,1,1,0,1,0,0,0,0,1,0,1,0
6,deklarasi pilkada 2018 aman dan anti hoax warg...,0,0,0,0,0,0,0,0,0,0,0,0
7,Gue baru aja kelar re-watch Aldnoah Zero!!! pa...,0,1,0,0,0,0,0,0,0,0,0,0
8,Nah admin belanja satu lagi port terbaik nak m...,0,0,0,0,0,0,0,0,0,0,0,0
9,USER Enak lg klo smbil ngewe',0,1,0,0,0,0,0,0,0,0,0,0
10,"Setidaknya gw punya jari tengah buat lu, sebel...",1,1,1,0,0,0,0,0,1,1,0,0
11,USER USER USER USER BANCI KALENG MALU GA BISA ...,1,1,1,0,0,0,0,1,0,1,0,0
12,Kalo belajar ekonomi mestinya jago memprivatis...,0,0,0,0,0,0,0,0,0,0,0,0
13,Aktor huruhara 98 Prabowo S ingin lengserkan p...,1,0,1,0,0,0,0,0,1,1,0,0
14,USER Bu guru enakan jadi jablay atau guru esde...,1,1,1,0,0,0,0,1,0,1,0,0

### Cek shape data hatespeech dari data uji

0    7608
1    5561
Name: HS, dtype: int64

### Cek shape data abusive dari data uji

0    8126
1    5043
Name: Abusive, dtype: int64

if hatespeech dan abusive == 1, then toxic.

if hatespeech dan abusive == 0, then non-toxis.

Toxic shape:   (7309, 13)
Non-toxic shape:  (5860, 13)

## Cek shape data alay

Shape:  (15167, 2)

               original               replacement
0   anakjakartaasikasik  anak jakarta asyik asyik
1          pakcikdahtua         pak cik sudah tua
2        pakcikmudalagi         pak cik muda lagi
3           t3tapjokowi              tetap jokowi
4                    3x                 tiga kali
5                aamiin                      amin
6               aamiinn                      amin
7                 aamin                      amin
8               aammiin                      amin
9                  abis                     habis
10               abisin                  habiskan
11                 acau                     kacau
12                achok                      ahok
13                   ad                       ada
14                 adek                      adik

## Buat fungsi cleaning regex

Hapus alphanumeric:  Halooo duniaa
konversi ke lowercase:  rt user halooo, duniaa!
Hapus karakter yang tidak perlu:  Hehe RT USER USER apa kabs hehe
Normalisasi kata-kata alay:  ahok
Hapus kata-kata kasar:   kau

## Gabungkan seluruh fungsi

## Terapkan fungsi cleaning abusive dan alay ke data uji

## Lihat hasil dari machine learning sederhana (regex dan pandas)

Shape:  (13169, 13)

,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,di saat semua cowok berusaha melacak perhatia...,1,1,1,0,0,0,0,0,1,1,0,0
1,siapa yang telat memberi tau kamu gue berga...,0,1,0,0,0,0,0,0,0,0,0,0
2,41 kadang aku berpikir kenapa aku tetap percay...,0,0,0,0,0,0,0,0,0,0,0,0
3,aku itu aku dan ku tau matamu tapi dilihat d...,0,0,0,0,0,0,0,0,0,0,0,0
4,kaum ce sudah kelihatan nya dari awal tambah...,1,1,0,1,1,0,0,0,0,0,1,0
5,ya dan kawan kawan xf0 x9f x98 x84 xf0 x9f ...,1,1,0,1,0,0,0,0,1,0,1,0
6,deklarasi pilihan kepala daerah 2018 aman dan ...,0,0,0,0,0,0,0,0,0,0,0,0
7,gue baru saja selesai re watch aldnoah zero pa...,0,1,0,0,0,0,0,0,0,0,0,0
8,nah admin belanja satu lagi po terbaik nak mak...,0,0,0,0,0,0,0,0,0,0,0,0
9,enak lagi kalau sambil,0,1,0,0,0,0,0,0,0,0,0,0
10,setidaknya gue punya jari tengah buat kamu seb...,1,1,1,0,0,0,0,0,1,1,0,0
11,kaleng malu tidak bisa jawab pe anyaan kami ...,1,1,1,0,0,0,0,1,0,1,0,0
12,kalau belajar ekonomi mestinya jago memprivati...,0,0,0,0,0,0,0,0,0,0,0,0
13,aktor huru hara 98 prabowo si ingin kan pemeri...,1,0,1,0,0,0,0,0,1,1,0,0
14,bu guru enakan jadi atau guru sekolah dasar ...,1,1,1,0,0,0,0,1,0,1,0,0

## Save ke SQlite

In [14]:
# coba baca dulu dtaframe

output cleansing tweet sudah tersimpan ke database